[build]
  command = "npm run build && curl -X GET https://orcatech.netlify.app/.netlify/functions/ping-search-engines"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[edge_functions]]
path = "/.netlify/functions/articles"
function = "articles"